import type { Project } from './schema'

// Worked example: urban commute mode choice in a European city.
// 4 alternatives: Car, Public transport, Bike, Walking. 4 attributes,
// 6 choice tasks across 2 blocks. Demonstrates a labeled experiment with
// alternative-specific attributes (cost on Car/PT only, service frequency
// on PT only).

export const travelModeExample: Project = {
  id: 'proj_eu_mode_choice',
  slug: 'eu-urban-commute',
  name: 'Urban Commute Mode Choice (EU)',
  description:
    'Stated-preference study of commuting decisions across four travel modes in a mid-size European city.',
  createdAt: '2026-04-27T10:00:00Z',
  updatedAt: '2026-04-27T10:05:00Z',
  experimentType: 'labeled',
  targetSampleSize: 400,

  alternatives: [
    { id: 'car', label: 'Car', isOptOut: false, position: 0 },
    { id: 'pt', label: 'Public transport', isOptOut: false, position: 1 },
    { id: 'bike', label: 'Bike', isOptOut: false, position: 2 },
    { id: 'walk', label: 'Walking', isOptOut: false, position: 3 },
  ],

  attributes: [
    {
      id: 'travel_time',
      name: 'Travel time',
      type: 'numeric',
      unit: 'min',
      displayFormat: 'duration',
      preferenceDirection: 'lower',
      appliesTo: 'all',
      position: 0,
      levels: [
        { id: 'tt_15', value: 15, displayValue: '15 min', position: 0 },
        { id: 'tt_30', value: 30, displayValue: '30 min', position: 1 },
        { id: 'tt_45', value: 45, displayValue: '45 min', position: 2 },
      ],
    },
    {
      id: 'cost',
      name: 'Cost',
      type: 'numeric',
      unit: 'EUR',
      displayFormat: 'currency',
      preferenceDirection: 'lower',
      appliesTo: ['car', 'pt'],
      position: 1,
      levels: [
        { id: 'cost_1', value: 1.0, displayValue: '€1.00', position: 0 },
        { id: 'cost_3', value: 3.0, displayValue: '€3.00', position: 1 },
        { id: 'cost_6', value: 6.0, displayValue: '€6.00', position: 2 },
      ],
    },
    {
      id: 'comfort',
      name: 'Comfort',
      type: 'categorical',
      preferenceDirection: 'higher',
      appliesTo: 'all',
      position: 2,
      levels: [
        { id: 'comf_low', value: 'Low', position: 0 },
        { id: 'comf_med', value: 'Medium', position: 1 },
        { id: 'comf_high', value: 'High', position: 2 },
      ],
    },
    {
      id: 'service_frequency',
      name: 'Service frequency',
      type: 'numeric',
      unit: 'min',
      displayFormat: 'duration',
      preferenceDirection: 'lower',
      appliesTo: ['pt'],
      position: 3,
      levels: [
        { id: 'sf_5', value: 5, displayValue: 'Every 5 min', position: 0 },
        { id: 'sf_10', value: 10, displayValue: 'Every 10 min', position: 1 },
        { id: 'sf_20', value: 20, displayValue: 'Every 20 min', position: 2 },
      ],
    },
  ],

  contextVariables: [
    {
      id: 'weather',
      name: 'Weather',
      type: 'categorical',
      position: 0,
      levels: [
        { id: 'wx_sunny', value: 'Sunny', position: 0 },
        { id: 'wx_cloudy', value: 'Cloudy', position: 1 },
        { id: 'wx_rainy', value: 'Rainy', position: 2 },
      ],
    },
    {
      id: 'purpose',
      name: 'Travel purpose',
      type: 'categorical',
      position: 1,
      levels: [
        { id: 'pp_commute', value: 'Commuting', position: 0 },
        { id: 'pp_leisure', value: 'Leisure', position: 1 },
        { id: 'pp_shop', value: 'Shopping', position: 2 },
      ],
    },
  ],

  design: {
    source: 'csv',
    uploadedAt: '2026-04-27T10:05:00Z',
    filename: 'eu_mode_choice.csv',
    numTasks: 6,
    numBlocks: 2,
    rawHeaders: [
      'choice_task',
      'block',
      'car_travel_time',
      'car_cost',
      'car_comfort',
      'pt_travel_time',
      'pt_cost',
      'pt_comfort',
      'pt_service_frequency',
      'bike_travel_time',
      'bike_comfort',
      'walk_travel_time',
      'walk_comfort',
      'weather',
      'purpose',
    ],
    mapping: [
      { csvColumn: 'choice_task', role: 'task' },
      { csvColumn: 'block', role: 'block' },
      { csvColumn: 'car_travel_time', role: 'cell', alternativeId: 'car', attributeId: 'travel_time' },
      { csvColumn: 'car_cost', role: 'cell', alternativeId: 'car', attributeId: 'cost' },
      { csvColumn: 'car_comfort', role: 'cell', alternativeId: 'car', attributeId: 'comfort' },
      { csvColumn: 'pt_travel_time', role: 'cell', alternativeId: 'pt', attributeId: 'travel_time' },
      { csvColumn: 'pt_cost', role: 'cell', alternativeId: 'pt', attributeId: 'cost' },
      { csvColumn: 'pt_comfort', role: 'cell', alternativeId: 'pt', attributeId: 'comfort' },
      { csvColumn: 'pt_service_frequency', role: 'cell', alternativeId: 'pt', attributeId: 'service_frequency' },
      { csvColumn: 'bike_travel_time', role: 'cell', alternativeId: 'bike', attributeId: 'travel_time' },
      { csvColumn: 'bike_comfort', role: 'cell', alternativeId: 'bike', attributeId: 'comfort' },
      { csvColumn: 'walk_travel_time', role: 'cell', alternativeId: 'walk', attributeId: 'travel_time' },
      { csvColumn: 'walk_comfort', role: 'cell', alternativeId: 'walk', attributeId: 'comfort' },
      { csvColumn: 'weather', role: 'context', contextVariableId: 'weather' },
      { csvColumn: 'purpose', role: 'context', contextVariableId: 'purpose' },
    ],
    rows: [
      {
        taskId: 1,
        block: 1,
        cells: {
          'car.travel_time': 'tt_30',
          'car.cost': 'cost_3',
          'car.comfort': 'comf_med',
          'pt.travel_time': 'tt_45',
          'pt.cost': 'cost_1',
          'pt.comfort': 'comf_high',
          'pt.service_frequency': 'sf_10',
          'bike.travel_time': 'tt_30',
          'bike.comfort': 'comf_med',
          'walk.travel_time': 'tt_45',
          'walk.comfort': 'comf_low',
        },
        context: { weather: 'wx_sunny', purpose: 'pp_commute' },
      },
      {
        taskId: 2,
        block: 1,
        cells: {
          'car.travel_time': 'tt_15',
          'car.cost': 'cost_6',
          'car.comfort': 'comf_high',
          'pt.travel_time': 'tt_30',
          'pt.cost': 'cost_3',
          'pt.comfort': 'comf_med',
          'pt.service_frequency': 'sf_5',
          'bike.travel_time': 'tt_15',
          'bike.comfort': 'comf_low',
          'walk.travel_time': 'tt_30',
          'walk.comfort': 'comf_high',
        },
        context: { weather: 'wx_cloudy', purpose: 'pp_leisure' },
      },
      {
        taskId: 3,
        block: 1,
        cells: {
          'car.travel_time': 'tt_45',
          'car.cost': 'cost_1',
          'car.comfort': 'comf_low',
          'pt.travel_time': 'tt_15',
          'pt.cost': 'cost_6',
          'pt.comfort': 'comf_med',
          'pt.service_frequency': 'sf_20',
          'bike.travel_time': 'tt_45',
          'bike.comfort': 'comf_high',
          'walk.travel_time': 'tt_15',
          'walk.comfort': 'comf_med',
        },
        context: { weather: 'wx_rainy', purpose: 'pp_shop' },
      },
      {
        taskId: 4,
        block: 2,
        cells: {
          'car.travel_time': 'tt_30',
          'car.cost': 'cost_6',
          'car.comfort': 'comf_high',
          'pt.travel_time': 'tt_15',
          'pt.cost': 'cost_1',
          'pt.comfort': 'comf_low',
          'pt.service_frequency': 'sf_5',
          'bike.travel_time': 'tt_30',
          'bike.comfort': 'comf_med',
          'walk.travel_time': 'tt_30',
          'walk.comfort': 'comf_med',
        },
        context: { weather: 'wx_sunny', purpose: 'pp_leisure' },
      },
      {
        taskId: 5,
        block: 2,
        cells: {
          'car.travel_time': 'tt_45',
          'car.cost': 'cost_3',
          'car.comfort': 'comf_med',
          'pt.travel_time': 'tt_30',
          'pt.cost': 'cost_6',
          'pt.comfort': 'comf_high',
          'pt.service_frequency': 'sf_20',
          'bike.travel_time': 'tt_15',
          'bike.comfort': 'comf_low',
          'walk.travel_time': 'tt_45',
          'walk.comfort': 'comf_low',
        },
        context: { weather: 'wx_cloudy', purpose: 'pp_shop' },
      },
      {
        taskId: 6,
        block: 2,
        cells: {
          'car.travel_time': 'tt_15',
          'car.cost': 'cost_1',
          'car.comfort': 'comf_low',
          'pt.travel_time': 'tt_45',
          'pt.cost': 'cost_3',
          'pt.comfort': 'comf_low',
          'pt.service_frequency': 'sf_10',
          'bike.travel_time': 'tt_45',
          'bike.comfort': 'comf_high',
          'walk.travel_time': 'tt_15',
          'walk.comfort': 'comf_high',
        },
        context: { weather: 'wx_rainy', purpose: 'pp_commute' },
      },
    ],
  },

  builder: {
    attributeOrder: ['travel_time', 'cost', 'comfort', 'service_frequency'],
    alternativeOrder: ['car', 'pt', 'bike', 'walk'],
    layout: 'attributes-as-rows',
    showUnits: true,
    optOutPosition: 'last',
  },
}
